services:
  scdl:
    build: .
    container_name: soundcloud-downloader
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: host
    privileged: true
    volumes:
      - /mnt/g/soundcloud-downloader/jake_lindsey:/Music/SoundCloud/jake_lindsey
      - ~/.config/scdl:/root/.config/scdl
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"] 
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    logging:
      options:
        max-size: "10m"
        max-file: "3"
